### ISSUE TITLE
[Feature request] service name in "feathers-plus generate service" command

### ISSUE THREAD

**Issue by iva2k** [feathers-plus/cli#10]
### Steps to reproduce

Would be nice to have a quicker way to re-generate:

```
$ feathers-plus generate service users -y
```

### Expected behavior
Regenerates service "users" (or whatever the given name is) without prompts & keeping defaults.
If service does not exist yet, should generate the service with all defaults.

### Actual behavior
What happens instead:
```
$ feathers-plus generate service users -y
error: unknown option `-y'
```

Without '-y':
```
$ feathers-plus generate service users
  What is the name of the service?
```

**Comment by iva2k** [comment]
@eddyystop Thanks! I will explore that path, sounds promising.
Makes sense to use ```generate all```, especially that typings.d.ts is updated in ```generate all```, so need to run it after almost always.

Thinking out loud - it is almost like there should be another command, maybe ```generate options --add-sevice <name>``` that will only edit the feathers-gen-specs.json file...

**Comment by eddyystop** [comment]
typings.d.ts is now regenerated whenever it needs to be. There is no need to run a spurious `generate all` anymore.

I'd rather people use their IDE to edit feathers-gen-specs.json. There is less chance of syntax errors.
