### ISSUE TITLE
Problems generating app or options

### ISSUE THREAD

**Issue by kokujin** [feathers-plus/cli#16]
I am using a fresh install of the cli, using the documentation, I tried the commands:

feathers-plus generate options
feathers-plus generate app

Both failed out with the error below. Can someone confirm this?

```````
Error: Cannot find module 'json-schema-seeder'
```````

**Comment by eddyystop** [comment]
Oops. That's because `generate seeder` was just added for beta testing.

**Comment by eddyystop** [comment]
Fix published at f+/cli v0.5.1 using generator v0.3.1.
