### ISSUE TITLE
feathers-plus generate fakes

### ISSUE THREAD

**Issue by bsa-git** [feathers-plus/cli#18]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by bsa-git** [comment]
I tried to execute the command- "feathers-plus generate fakes", but the command was not executed. A message was displayed - [json-schema-faker] calling JsonSchemaFaker () is deprecated, call either .generate () or .resolve ().
What would it mean?

**Comment by eddyystop** [comment]
A dependency introduced a breaking change without without bumping the major number in its semver. I'll provide a fix for the generator once I see what changes were introduced in that dependency.

**Comment by eddyystop** [comment]
The dependency of a dependency has changed and is also having some issues. I've presently locked them down to versions that work.

`npm i -g @feathers-plus/cli` the latest version. Clear your NPM cache if the fakes issue remains. NPM sometimes uses incorrect versions.

Published as f+/cli v0.7.42 which runs generator v0.6.41.

Please let me know your results. Thanks.

**Comment by eddyystop** [comment]
People settled down on creating issues under feather-plus/generator-feathers-plus . Perhaps its best we all use that.
