### ISSUE TITLE
Generate test for base authentication

### ISSUE THREAD

**Issue by bsa-git** [feathers-plus/cli#19]
When you run this test, an error occurs. Wrong email format...
The error may be in the file: "C:/NodeServer/feathers-plus-app/node_modules/@feathers-plus/test-utils/lib/cli/authentication.base.js"
...
`const loginEmail = 'hdsjkhsdkhfhfdhgfjffghfghfghfh';`
...

**Comment by eddyystop** [comment]
Good point.

What adapter and DB are you using? Did you define validation checking on the DB model itself, or perhaps add a validation hook on the service?

**Comment by bsa-git** [comment]
1. I am using an "mongoose" adapter for the database. 
2. I am using a alidation hook on the service.

**Comment by eddyystop** [comment]
Thanks for this catch.

Changed in both test modules to
```js
const loginEmail = 'hdsjkhsdkhfhfd@hgfjffghfgh.com';
```

Published as v0.3.4. I think you can just install that over your generated app.
