### ISSUE TITLE
Local commands

### ISSUE THREAD

**Issue by samburgers** [feathers-plus/cli#20]
Might be one for the feathers-plus generator, rather than here, but is there any plan to have the generate cli commands available as a local `devDependencies`, so any collaborators aren't required to install globally?

Thanks!

**Comment by eddyystop** [comment]
Others contributors have not raised this as an issue. I would think you can install it in a folder, add that folder to the PATH, and create a shell command to call it.

**Comment by samburgers** [comment]
Thanks for the reply! Did a bit of further testing... it's not perfect, but if anyone else is interested in local feathers-plus CLI only, these steps get pretty close to global parity:

### Fresh Project
```
yarn init -y

yarn add @feathers-plus/cli --dev
```

Add to `package.json`

```
"scripts": {
  "fp": "feathers-plus",
},
```

Now you can run all commands locally like so:

`yarn fp generate app`
`yarn fp generate service`

Worth noting after i generated a fresh app, i had to manually add these to the package.json

```
"scripts": {
  ...
  "dev": "nodemon src/",
  "start": "node src/",
   ...
}
```

**Comment by eddyystop** [comment]
This is useful info. Thanks!

Could you confirm having to add dev and start? They are generated with everything else in package.json on `generate app`.

**Comment by samburgers** [comment]
for some reason the `yarn fs generate app` command only adds these to scripts with the above method

```
  "test:all": "yarn run eslint && NODE_ENV= npm run mocha",
  "start:seed": "NODE_ENV= node src/ --seed"
```

Assume its because one of the yeoman tasks is probably to create a package.json with the above scripts if it doesnt exist, however we are creating the package.json during `yarn init` in my example

**Comment by eddyystop** [comment]
You already have a package.json in the folder when you run `generate app`. cli+ does not expect that and results are whatever.

What are doing with cli+?
