### ISSUE TITLE
Use https on new Feathers (Buzzard) with typescript

### ISSUE THREAD

**Issue by vigalo** [feathers-plus/cli#22]
Hello: 
I'm trying to update my feathers server from Auk to the new Buzzard. I'm using the new feathers-plus cli because i'm interested in using typescript on server, and GraphicQL.

My old Auk server is working correctly with https configuration, loading the certs and initializing the app : 

`const fs = require('fs');
const https = require('https');

const privateKey = fs.readFileSync('/etc/ssl/private/sigalo.key');
const certificate = fs.readFileSync('/etc/ssl/certs/sigalo.cert');
const ca = fs.readFileSync('/etc/ssl/certs/www_sigalo_es.ca-bundle');

const credentials = {key: privateKey, cert: certificate, ca: ca};

const server = https.createServer(credentials, app).listen(8282);

app.setup(server);
` 

But now, with the new generated app.ts generated by cli+ I don't know how to make it to work and where is the correct block where tu put the imports, initialization, etc to avoid lose it in regeneration.

Can you help me?
Thanks

**Comment by eddyystop** [comment]
You can always freeze a module, preventing it from being regenerated, by adding its path to options.freeze in feathers-gen-specs.json. For example
```js
freeze: [ 'src/app.js' ],
```

Would you mind sending me a diff between a normally generated module and your once you have https implemented. We may want to make https support a cli+ option.

**Comment by eddyystop** [comment]
I'm moving this issue to feathers-plus/generate-feathers-plus

https://github.com/feathers-plus/generator-feathers-plus/issues/111

**Comment by vigalo** [comment]
> You can always freeze a module, preventing it from being regenerated, by adding its path to options.freeze in feathers-gen-specs.json. For example
> 
> ```js
> freeze: [ 'src/app.js' ],
> ```
> 
> Would you mind sending me a diff between a normally generated module and your once you have https implemented. We may want to make https support a cli+ option.


Ok, thanks.

I attach the diff of index.ts once https implemented, as you requested.
[diff.txt](https://github.com/feathers-plus/cli/files/2609062/diff.txt)

**Comment by eddyystop** [comment]
How do I use that diff.txt? Alternatively you send me your version of the changed modules and I can diff them myself.

**Comment by vigalo** [comment]
Hello 
I only changed index.ts as is attached : 

[index.zip](https://github.com/feathers-plus/cli/files/2611258/index.zip)

**Comment by eddyystop** [comment]
Thanks!
