### ISSUE TITLE
Best practices of using generate with prettier

### ISSUE THREAD

**Issue by sergdort** [feathers-plus/cli#24]
Hey, thank you very much for your work 👍

I'm kind of noob in the JS world :)

Just wondering if there is a best practices to use cli `generate` with [prettier](https://prettier.io), as I'm getting a lot of changes after generate.

Cheers.

**Comment by eddyystop** [comment]
I believe we can close this issue now.

**Comment by sergdort** [comment]
Thanks, what we ended up doing is we running Prettier after feathers generate ¯\_(ツ)_/¯
