### ISSUE TITLE
app#src with multiple path directory fail to start

### ISSUE THREAD

**Issue by zucher** [feathers-plus/cli#30]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.

If you define during creation an app source folder in a subdirectory, on launch the path app.js doesn't reflect the right path:
for "src": "app/modules/server"
we have
const generatorSpecs = require('../feathers-gen-specs.json');
instead of:

const generatorSpecs = require('../../../feathers-gen-specs.json');

- [x ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

"app": {
    "environmentsAllowingSeedData": "",
    "seedData": false,
    "name": "xxxx",
    "description": "Project xxxx",
    "src": "app/modules/server",
    "packager": "yarn@>= 0.18.0",
    "providers": [
      "rest",
      "socketio"
    ]
  }

### Expected behavior
Tell us what should happen
see above

### Actual behavior
Tell us what happens instead
see above
### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
feathersjs-plus generate app / feathersjs-plus generate all

**NodeJS version**:
v10.15.1
**Operating System**:
Windows LWS / Debian

**Browser Version**:
none
**React Native Version**:
none
**Module Loader**:
yarn

**Comment by eddyystop** [comment]
The "src" directory cannot be a path in either cli+ or featerjs/cli. Neither the docs nor the prompt suggest it can be a path.

**Comment by zucher** [comment]
thank you for this notice.
