### ISSUE TITLE
[Question] "mongo" & "sequelize" files for "mongoose"?

### ISSUE THREAD

**Issue by J05HI** [feathers-plus/cli#35]
Why does the CLI generate the "x.mongo.xx" & "x.sequelize.xx" files if I choose "mongoose"?

![image](https://user-images.githubusercontent.com/16399787/55274799-b4bbcc80-52dc-11e9-8457-23241cc1f3dd.png)

![image](https://user-images.githubusercontent.com/16399787/55274781-92c24a00-52dc-11e9-8cd4-4e2d6a26eab0.png)

**Comment by eddyystop** [comment]
One of FeathersJS features is being able to switch between different DBs. cli+ supports this by creating modules for multiple DBs. This allows you to add custom code for each DB and not lose it when you switch DBs.

**Comment by J05HI** [comment]
@eddyystop
Thanks for the fast response! 
So I can delete them if I don't need multi db support.

**Comment by eddyystop** [comment]
You can delete them. Dome commands may recreate them unless you freeze them in feathers-gen-soecs.json in options.freeze

**Comment by J05HI** [comment]
@eddyystop
Amazing! The freeze option is what I'm looking for :)
