### ISSUE TITLE
generate hook misssing

### ISSUE THREAD

**Issue by SassNinja** [feathers-plus/cli#7]
If I've understood correctly feathers-plus is supposed to offer the same features as feathers cli (plus additional ones), isn't it?

I tried to generate a hook via
```bash
feathers-plus generate hook
```
but this command doesn't seem to be supported

Has it been forgotten?

**Comment by eddyystop** [comment]
We decided not to include `generate hook`. First its not possible to correctly position a call to the hook in `serviceName.hooks.?s`. Second, adding hooks manually is trivial.

The most we could do is create an empty module for the hook and `require` it in `serviceName.hooks.?s`.

**Comment by SassNinja** [comment]
> The most we could do is create an empty module for the hook and require it in `serviceName.hooks.?s`. - @eddyystop 

Then it would be almost the same as feathers cli.
It may be trivial but nevertheless I think it's a nice helper, to not forget the test.

**Comment by eddyystop** [comment]
I agree. It seems I discounted this too easily. I'll leave this as a to do.

**Comment by eddyystop** [comment]
Sorry, issues under feathers-plus/cli don't get reviewed much at all. Most issues are created under feathers-plus/generator-feathers-plus.

`generate hook` was implemented and documented some time ago.
